apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grep-ingress
  namespace: grep
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: grep.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grep-service
                port:
                  number: 80
